### ISSUE TITLE
Create oAuthToken model

### ISSUE THREAD

**Issue by the-vampiire** [Chingu-Core-Components/AutoBot#15]
Create the oAuthToken model that will store oAuthTokens from all registered Slack teams (cohorts). 

- oAuthTokens will be set via the setOAuthToken function which is called during team registration at the oAuth redirect request url 

- oAuthTokens will be retrievable via the getOAuthToken function

**Comment by the-vampiire** [comment]
Need to capture the following fields in the model:

- oAuthToken (Slack team)
- oAuthToken (bot user)
- bot slack ID (per team)

![screen shot 2017-09-05 at 3 17 20 am](https://user-images.githubusercontent.com/25523682/30049477-dd77275c-91e8-11e7-8c1a-86bf7a7cedeb.png)

**Comment by dsegovia90** [comment]
I've done this before, I could work on it today.

**Comment by the-vampiire** [comment]
Closed in last merge
